"""
remote_access/ssh_config_exporter.py
Bulk SSH config generator for Server Operations.

Converts server_connections (protocol=ssh) into an OpenSSH-compatible
~/.ssh/config block for preview/download.

Security constraints:
- Never writes to disk automatically.
- Never includes passwords, credential_ref secrets, or any auth material
  other than key file paths (which the user already owns).
- Host alias sanitisation prevents injection of OpenSSH keywords.
"""
from __future__ import annotations

import re
from typing import Any

# OpenSSH keywords that must not appear as Host aliases (injection guard)
_BLOCKED_ALIASES: frozenset[str] = frozenset({
    "host", "match", "include",
})

# Characters valid in an OpenSSH Host alias: alphanumeric, -, _, ., *
_ALIAS_SAFE = re.compile(r"[^a-zA-Z0-9\-_\.]")


def _sanitize_alias(name: str, conn_id: str) -> tuple[str, str | None]:
    """Return (safe_alias, warning_or_None)."""
    if not name:
        return f"host-{conn_id[:8]}", "Empty name; fallback alias used"

    # Replace spaces with hyphens first, then strip remaining bad chars
    safe = name.replace(" ", "-")
    safe = _ALIAS_SAFE.sub("", safe)

    # Remove leading dots/hyphens
    safe = safe.lstrip(".-")

    if not safe:
        safe = f"host-{conn_id[:8]}"
        return safe, f"Name '{name}' produced empty alias; fallback used"

    if safe.lower() in _BLOCKED_ALIASES:
        safe = f"conn-{safe}"
        return safe, f"Name '{name}' clashes with OpenSSH keyword; renamed to '{safe}'"

    warn = None
    if safe != name:
        warn = f"Name '{name}' sanitised to alias '{safe}'"
    return safe, warn


def generate_ssh_config(connections: list[dict[str, Any]]) -> dict[str, Any]:
    """Generate an OpenSSH config preview from a list of connection dicts.

    Only ``protocol == "ssh"`` connections are included.
    Returns::

        {
          "status": "ok",
          "host_count": int,
          "config": str,
          "warnings": [str, ...]
        }
    """
    warnings: list[str] = []
    blocks: list[str] = []
    seen_aliases: dict[str, str] = {}  # alias -> connection id (duplicate guard)

    ssh_conns = [c for c in connections if (c.get("protocol") or "ssh") == "ssh"]

    for conn in ssh_conns:
        cid   = conn.get("id", "")
        name  = (conn.get("name") or "").strip()
        host  = (conn.get("hostname") or conn.get("ip") or "").strip()
        user  = (conn.get("username") or "").strip()
        port  = conn.get("port", 22)
        key   = (conn.get("key_ref") or "").strip()
        tags  = conn.get("tags") or []
        uhid  = (conn.get("unified_host_id") or "").strip()
        notes = (conn.get("notes") or "").strip()

        if not host:
            warnings.append(f"Connection '{name}' ({cid}) has no hostname/IP — skipped")
            continue

        alias, warn = _sanitize_alias(name, cid)
        if warn:
            warnings.append(warn)

        # Duplicate alias guard
        if alias in seen_aliases:
            alias = f"{alias}-{cid[:6]}"
            warnings.append(
                f"Duplicate alias; renamed to '{alias}' "
                f"(conflicts with connection {seen_aliases.get(alias.rsplit('-', 1)[0])})"
            )
        seen_aliases[alias] = cid

        # Validate IdentityFile path — must not contain shell metacharacters
        safe_key = ""
        if key:
            if re.search(r"[;&|`$><\n\r]", key):
                warnings.append(
                    f"Connection '{name}': key_ref contains unsafe characters — IdentityFile omitted"
                )
            else:
                safe_key = key

        lines: list[str] = []

        # Comment header
        if tags:
            lines.append(f"# Tags: {', '.join(tags)}")
        if uhid:
            lines.append(f"# Unified Host: {uhid}")
        if notes:
            # Inline note (first line only, stripped)
            note_line = notes.splitlines()[0][:80]
            lines.append(f"# Note: {note_line}")

        lines.append(f"Host {alias}")
        lines.append(f"    HostName {host}")
        if user:
            lines.append(f"    User {user}")
        if port and int(port) != 22:
            lines.append(f"    Port {port}")
        if safe_key:
            lines.append(f"    IdentityFile {safe_key}")
            lines.append("    IdentitiesOnly yes")
        lines.append("    ServerAliveInterval 60")
        lines.append("    ServerAliveCountMax 3")

        blocks.append("\n".join(lines))

    header = (
        "# Generated by Wazuh AI Analyzer — Server Operations\n"
        "# Mode: read-only preview — NOT written to disk automatically.\n"
        "# Review carefully before appending to ~/.ssh/config.\n"
        "# Passwords are never included.\n"
    )
    config = header + "\n" + "\n\n".join(blocks) if blocks else header

    return {
        "status": "ok",
        "host_count": len(blocks),
        "config": config,
        "warnings": warnings,
    }
