/**
 * Mock LiveEventCluster objects for frontend testing / demo mode.
 * These simulate what /event-map/live returns after backend enrichment.
 * Use in EventConstellationView demo mode or Storybook.
 */

import type { LiveEventCluster } from './api';

const NOW = new Date().toISOString();
const MINUS5 = new Date(Date.now() - 5 * 60_000).toISOString();
const MINUS30 = new Date(Date.now() - 30 * 60_000).toISOString();

// ── Win 4625: Brute-force / failed logon ──────────────────────────────────────
export const mockCluster4625: LiveEventCluster = {
  id: 'mock-win-4625',
  kind: 'event_id',
  title: 'Multiple Failed Logon Attempts',
  severity: 'high',
  alertCount: 230,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'FS-01.corp.local', ip: '10.0.5.18', count: 195 }],
  users: [{ name: 'guest', count: 230 }],
  processes: [{ name: 'lsass.exe', count: 230 }],
  sourceIps: [{ ip: '192.168.56.23', count: 188 }],
  ruleIds: ['60122'],
  eventIds: ['4625'],
  mitreTactics: ['Credential Access'],
  mitreIds: ['T1110'],
  firstSeen: MINUS30,
  lastSeen: MINUS5,
  shortExplanation: 'Repeated failed network logon attempts for disabled guest account.',
  recommendedActions: ['Investigate source IP', 'Check for successful logon after failure burst'],
  knowledge: {
    key: 'win_4625',
    title: 'Failed Logon (4625)',
    category: 'authentication',
    default_severity: 'high',
    summary: 'Windows Event 4625 records failed logon attempts. Repeated failures, especially for disabled accounts or from a single source IP, indicate credential stuffing, brute-force, or password spraying.',
    knowledge_level: 'deep',
    platform: 'windows',
  },
  evidence_summary: {
    top_user: 'guest',
    top_source_ip: '192.168.56.23',
    top_process: 'lsass.exe',
    logon_type: '3',
    status: '0xC000006A',
    sub_status: '0xC0000064',
  },
  playbooks: [
    {
      playbook_id: 'win_brute_force_v1',
      title: 'Windows Brute-Force / Credential Spray',
      description: 'Investigate repeated 4625 failures for signs of automated password attack. Correlate with successful logons (4624) and lateral movement.',
      recommended_checks: [
        'Check if source IP is internal, VPN or external',
        'Count distinct accounts targeted by same source IP',
        'Check for 4624 success events after failure burst',
        'Review account lockout status in AD',
        'Verify guest account is truly disabled',
      ],
      recommended_readonly_scripts: ['win_get_failed_logons', 'win_get_logon_history', 'net_geo_lookup'],
      dangerous_actions: ['reset_password', 'block_firewall_ip', 'disable_account'],
      blocked_actions_reason: 'Credential and firewall changes require Change-Management approval.',
      escalation_conditions: ['Source IP seen on >5 accounts', '4624 success found from same IP', 'Admin account targeted'],
      false_positive_notes: ['Misconfigured service with saved wrong credentials', 'VPN client retry on failed DNS', 'Backup agent with expired credentials'],
    },
  ],
  rawPreview: {
    agent: { id: '001', name: 'FS-01.corp.local', ip: '10.0.5.18' },
    rule: { id: '60122', level: 10, description: 'Multiple authentication failures' },
    data: { win: { system: { eventID: '4625' }, eventdata: { subjectUserName: 'SYSTEM', targetUserName: 'guest', logonType: '3', ipAddress: '192.168.56.23', status: '0xC000006A', subStatus: '0xC0000064' } } },
    timestamp: MINUS5,
  },
};

// ── Win 7045: New service created ─────────────────────────────────────────────
export const mockCluster7045: LiveEventCluster = {
  id: 'mock-win-7045',
  kind: 'event_id',
  title: 'New Windows Service Created',
  severity: 'high',
  alertCount: 3,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'APP-02.corp.local', ip: '10.0.8.22', count: 3 }],
  users: [{ name: 'Administrator', count: 3 }],
  processes: [{ name: 'services.exe', count: 3 }],
  sourceIps: [],
  ruleIds: ['60602'],
  eventIds: ['7045'],
  mitreTactics: ['Persistence', 'Privilege Escalation'],
  mitreIds: ['T1543.003'],
  firstSeen: MINUS30,
  lastSeen: NOW,
  shortExplanation: 'A new Windows service was registered. Verify legitimacy of service binary and install source.',
  recommendedActions: ['Verify service binary path and signature', 'Check binary is not in Temp/AppData'],
  knowledge: {
    key: 'win_7045',
    title: 'New Service Installed (7045)',
    category: 'persistence',
    default_severity: 'high',
    summary: 'Event 7045 records a new service being installed on a Windows system. Malware commonly uses services for persistence. Check the service binary path for suspicious locations.',
    knowledge_level: 'deep',
    platform: 'windows',
  },
  evidence_summary: {
    top_user: 'Administrator',
    top_process: 'services.exe',
    service_name: 'WinDefUpdate',
    command_line: 'C:\\Windows\\Temp\\wdup.exe -svc',
    sensitive_path: 'C:\\Windows\\Temp\\wdup.exe',
    sensitive_reason: 'Service binary in %TEMP%',
  },
  playbooks: [
    {
      playbook_id: 'win_new_service_v1',
      title: 'Windows New Service — Persistence Check',
      description: 'Determine if the newly installed service is a legitimate application or malware persistence mechanism.',
      recommended_checks: [
        'Verify service binary path and digital signature',
        'Check if binary is in a suspicious location (Temp, AppData, Roaming)',
        'Correlate with software deployment events',
        'Look for parent process at install time (4688)',
        'Check hash against threat intel',
      ],
      recommended_readonly_scripts: ['win_get_services', 'win_get_autoruns', 'win_get_process_tree'],
      dangerous_actions: ['stop_service', 'delete_service', 'quarantine_file'],
      blocked_actions_reason: 'Service deletion and file quarantine require CISO approval.',
      escalation_conditions: ['Binary unsigned or hash matches known malware', 'Service name mimics Windows service', 'Binary in writable path'],
      false_positive_notes: ['EDR agent update', 'Patch management agent', 'Remote support tool (TeamViewer, AnyDesk)'],
    },
  ],
  rawPreview: {
    agent: { id: '002', name: 'APP-02.corp.local', ip: '10.0.8.22' },
    rule: { id: '60602', level: 10, description: 'New Windows service created' },
    data: { win: { system: { eventID: '7045' }, eventdata: { serviceName: 'WinDefUpdate', imagePath: 'C:\\Windows\\Temp\\wdup.exe -svc', serviceType: 'User Mode Service', startType: 'Auto Start', accountName: '.\\Administrator' } } },
    timestamp: NOW,
  },
};

// ── Linux: SSH failed login ───────────────────────────────────────────────────
export const mockClusterLinuxSSH: LiveEventCluster = {
  id: 'mock-linux-ssh',
  kind: 'rule',
  title: 'SSH Authentication Failures',
  severity: 'medium',
  alertCount: 512,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'srv-web01.internal', ip: '10.10.1.30', count: 512 }],
  users: [{ name: 'root', count: 390 }, { name: 'ubuntu', count: 122 }],
  processes: [{ name: 'sshd', count: 512 }],
  sourceIps: [{ ip: '45.129.56.100', count: 445 }],
  ruleIds: ['5716', '5763'],
  eventIds: [],
  mitreTactics: ['Credential Access'],
  mitreIds: ['T1110.001'],
  firstSeen: MINUS30,
  lastSeen: MINUS5,
  shortExplanation: 'Repeated SSH authentication failures from a single external IP, likely automated scanner.',
  recommendedActions: ['Check auth.log for successful SSH logins from same IP', 'Verify fail2ban status'],
  knowledge: {
    key: 'linux_ssh_failed',
    title: 'SSH Failed Login',
    category: 'authentication',
    default_severity: 'medium',
    summary: 'Repeated SSH login failures from one or a few source IPs indicate automated scanning or brute-force attack. Single attempt per user is normal noise; hundreds of attempts per source IP require investigation.',
    knowledge_level: 'deep',
    platform: 'linux',
  },
  evidence_summary: {
    top_user: 'root',
    top_source_ip: '45.129.56.100',
    top_process: 'sshd',
    logon_type: 'ssh',
    status: 'failed_password',
  },
  playbooks: [
    {
      playbook_id: 'linux_ssh_bruteforce_v1',
      title: 'Linux SSH Brute-Force Response',
      description: 'Investigate SSH failure burst. Determine if any attempt succeeded. Consider IP block at firewall or fail2ban.',
      recommended_checks: [
        'Check /var/log/auth.log for successful logins from same IP',
        'Verify if root SSH login is permitted in /etc/ssh/sshd_config',
        'Check fail2ban jail status for source IP',
        'Count unique usernames tried from source IP',
        'Verify SSH key auth is enforced for admin accounts',
      ],
      recommended_readonly_scripts: ['linux_get_auth_log', 'linux_get_sshd_config', 'linux_get_active_sessions', 'net_geo_lookup'],
      dangerous_actions: ['block_ip_firewall', 'disable_ssh', 'kill_session'],
      blocked_actions_reason: 'Firewall and SSH changes require change management approval.',
      escalation_conditions: ['Successful SSH login from same IP', 'root account targeted', 'Source IP on threat intel list'],
      false_positive_notes: ['Misconfigured monitoring agent', 'DevOps pipeline with wrong key', 'Honeypot intentional noise'],
    },
  ],
  rawPreview: {
    agent: { id: '030', name: 'srv-web01.internal', ip: '10.10.1.30' },
    rule: { id: '5716', level: 5, description: 'SSH: Multiple authentication failures' },
    location: '/var/log/auth.log',
    full_log: 'May 21 09:32:11 srv-web01 sshd[18432]: Failed password for invalid user root from 45.129.56.100 port 52312 ssh2',
    timestamp: MINUS5,
  },
};

// ── Linux: Sudo command ───────────────────────────────────────────────────────
export const mockClusterLinuxSudo: LiveEventCluster = {
  id: 'mock-linux-sudo',
  kind: 'rule',
  title: 'Suspicious Sudo Command',
  severity: 'high',
  alertCount: 4,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'dev-srv-04.internal', ip: '10.10.2.14', count: 4 }],
  users: [{ name: 'j.developer', count: 4 }],
  processes: [{ name: 'sudo', count: 4 }],
  sourceIps: [],
  ruleIds: ['5402'],
  eventIds: [],
  mitreTactics: ['Privilege Escalation', 'Execution'],
  mitreIds: ['T1548.003'],
  firstSeen: MINUS30,
  lastSeen: NOW,
  shortExplanation: 'Developer account executed privileged commands via sudo, including a base64-encoded shell command.',
  recommendedActions: ['Review sudoers for over-permissive entries', 'Decode base64 payload'],
  knowledge: {
    key: 'linux_sudo_cmd',
    title: 'Sudo Command Execution',
    category: 'privilege_escalation',
    default_severity: 'medium',
    summary: 'Sudo usage by non-admin users should be expected only for specific, pre-approved commands. Unusual commands, encoded payloads, or unexpected users escalating via sudo warrant investigation.',
    knowledge_level: 'deep',
    platform: 'linux',
  },
  evidence_summary: {
    top_user: 'j.developer',
    top_process: 'sudo',
    command_line: 'sudo bash -c "echo $PATH | base64 | sh"',
    sensitive_path: '/bin/bash',
    sensitive_reason: 'Shell invocation via sudo',
  },
  playbooks: [
    {
      playbook_id: 'linux_sudo_abuse_v1',
      title: 'Linux Sudo Abuse / Privilege Escalation',
      description: 'Determine if sudo usage is legitimate. Check for encoded commands, unexpected binaries, or NOPASSWD entries that bypass controls.',
      recommended_checks: [
        'Check /etc/sudoers and /etc/sudoers.d for over-permissive entries',
        'Review full sudo command from /var/log/auth.log',
        'Correlate with any new cron jobs or systemd units after the event',
        'Check if the user account was recently created or modified',
        'Verify whether encoded payload decodes to benign command',
      ],
      recommended_readonly_scripts: ['linux_get_sudo_log', 'linux_get_sudoers', 'linux_get_crontab', 'linux_get_auth_log'],
      dangerous_actions: ['revoke_sudo', 'lock_account', 'kill_session'],
      blocked_actions_reason: 'Account changes require HR and security sign-off.',
      escalation_conditions: ['Encoded command found in sudo history', 'NOPASSWD entry for ALL commands', 'Root shell spawned'],
      false_positive_notes: ['Build pipeline using sudo for package install', 'Docker container management', 'Automated patching script'],
    },
  ],
  rawPreview: {
    agent: { id: '014', name: 'dev-srv-04.internal', ip: '10.10.2.14' },
    rule: { id: '5402', level: 7, description: 'Sudo: Command run as root by non-root user' },
    location: '/var/log/auth.log',
    full_log: 'May 21 10:14:32 dev-srv-04 sudo: j.developer : TTY=pts/0 ; PWD=/home/j.developer ; USER=root ; COMMAND=/bin/bash -c echo $PATH | base64 | sh',
    timestamp: NOW,
  },
};

// ── Linux: FIM sensitive path ─────────────────────────────────────────────────
export const mockClusterLinuxFIM: LiveEventCluster = {
  id: 'mock-linux-fim',
  kind: 'rule',
  title: 'FIM Alert — Sensitive File Modified',
  severity: 'critical',
  alertCount: 2,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'db-master.internal', ip: '10.10.3.50', count: 2 }],
  users: [{ name: 'postgres', count: 2 }],
  processes: [],
  sourceIps: [],
  ruleIds: ['550', '554'],
  eventIds: [],
  mitreTactics: ['Defense Evasion', 'Persistence'],
  mitreIds: ['T1565.001'],
  firstSeen: MINUS5,
  lastSeen: NOW,
  shortExplanation: 'Wazuh FIM detected a modification to /etc/passwd, a critical system file.',
  recommendedActions: ['Diff /etc/passwd against baseline', 'Check for new UID=0 accounts'],
  knowledge: {
    key: 'linux_fim_sensitive',
    title: 'FIM — Sensitive File Changed',
    category: 'fim',
    default_severity: 'critical',
    summary: 'File Integrity Monitoring (FIM) detected modification of a sensitive system file. Changes to /etc/passwd, /etc/shadow, /etc/sudoers, or SSH configuration files are high-confidence IOCs for credential manipulation or persistence.',
    knowledge_level: 'deep',
    platform: 'linux',
  },
  evidence_summary: {
    file_path: '/etc/passwd',
    file_action: 'modified',
    sensitive_path: '/etc/passwd',
    sensitive_reason: 'Critical system credential file',
    top_user: 'postgres',
  },
  playbooks: [
    {
      playbook_id: 'linux_fim_critical_v1',
      title: 'FIM Critical Path — Possible Backdoor',
      description: 'Verify if the file change is authorized. Critical files like /etc/passwd should only change during known maintenance windows.',
      recommended_checks: [
        'Diff current /etc/passwd against last known-good baseline',
        'Check for newly added user accounts with UID 0',
        'Review process that triggered the change (Wazuh syscheck)',
        'Correlate with any recent sudo or SSH events',
        'Check if change occurred outside maintenance window',
      ],
      recommended_readonly_scripts: ['linux_get_passwd', 'linux_get_syscheck_diff', 'linux_get_auth_log', 'linux_get_active_sessions'],
      dangerous_actions: ['restore_file', 'lock_account', 'isolate_host'],
      blocked_actions_reason: 'File restoration and host isolation require Incident Commander approval.',
      escalation_conditions: ['New UID=0 account found', 'Change outside maintenance window', 'SSH keys modified in same window'],
      false_positive_notes: ['Scheduled package update (useradd system user)', 'Puppet/Chef configuration management run', 'Cloud-init on VM provisioning'],
    },
  ],
  rawPreview: {
    agent: { id: '050', name: 'db-master.internal', ip: '10.10.3.50' },
    rule: { id: '550', level: 7, description: 'Integrity checksum changed' },
    syscheck: { path: '/etc/passwd', event: 'modified', md5_after: 'a1b2c3d4e5f6...', md5_before: '9f8e7d6c5b4a...' },
    location: 'syscheck',
    timestamp: NOW,
  },
};

// ── Unknown / generic fallback cluster ───────────────────────────────────────
export const mockClusterUnknown: LiveEventCluster = {
  id: 'mock-unknown',
  kind: 'finding_type',
  title: 'Unknown Event Cluster',
  severity: 'medium',
  alertCount: 12,
  affectedHostCount: 1,
  affectedHosts: [{ hostname: 'host-unknown.corp.local', ip: '10.0.99.1', count: 12 }],
  users: [],
  processes: [],
  sourceIps: [],
  ruleIds: ['99001'],
  eventIds: ['99999'],
  mitreTactics: [],
  mitreIds: [],
  firstSeen: MINUS30,
  lastSeen: MINUS5,
  shortExplanation: 'Unrecognised event type. No knowledge entry available — use generic triage steps.',
  recommendedActions: ['Review raw alert data', 'Check rule definition in Wazuh manager'],
  knowledge: null,
  evidence_summary: undefined,
  playbooks: [],
  rawPreview: null,
};

/** All mock clusters, ordered by demo priority */
export const ALL_MOCK_CLUSTERS: LiveEventCluster[] = [
  mockCluster4625,
  mockCluster7045,
  mockClusterLinuxSSH,
  mockClusterLinuxSudo,
  mockClusterLinuxFIM,
  mockClusterUnknown,
];
